import { MusicCategory } from '../models';

// ============================================
// vibeOnly — Music Categories Data
// ============================================
// Each category has a recipe saying which sources it pulls from.

export const MUSIC_CATEGORIES: MusicCategory[] = [
  {
    id: 'bollywood',
    name: 'Bollywood',
    icon: 'bi-film',
    gradient: 'linear-gradient(135deg, #f6d365, #fda085)',
    tag: 'bollywood',
    description: 'Cinematic hits and Bollywood soundtracks',
    group: 'language',
    sources: { uploads: 'Bollywood', itunes: 'bollywood hits', audius: ['bollywood'] },
  },
  {
    id: 'hindi',
    name: 'Hindi',
    icon: 'bi-translate',
    gradient: 'linear-gradient(135deg, #ff9a9e, #fecfef)',
    tag: 'hindi',
    description: 'Hindi hits, indie-pop and soulful melodies',
    group: 'language',
    sources: { itunes: 'hindi songs', audius: ['hindi'] },
  },
  {
    id: 'punjabi',
    name: 'Punjabi',
    icon: 'bi-music-player-fill',
    gradient: 'linear-gradient(135deg, #4facfe, #00f2fe)',
    tag: 'punjabi',
    description: 'Energetic Punjabi beats and bhangra',
    group: 'language',
    sources: { itunes: 'punjabi', audius: ['punjabi'] },
  },
  {
    id: 'tamil',
    name: 'Tamil',
    icon: 'bi-music-note-beamed',
    gradient: 'linear-gradient(135deg, #ff512f, #dd2476)',
    tag: 'tamil',
    description: 'Kollywood hits and Tamil indie',
    group: 'language',
    sources: { itunes: 'tamil songs', audius: ['tamil'] },
  },
  {
    id: 'telugu',
    name: 'Telugu',
    icon: 'bi-music-note-beamed',
    gradient: 'linear-gradient(135deg, #f7971e, #ffd200)',
    tag: 'telugu',
    description: 'Tollywood blockbusters and melodies',
    group: 'language',
    sources: { itunes: 'telugu songs', audius: ['telugu'] },
  },
  {
    id: 'malayalam',
    name: 'Malayalam',
    icon: 'bi-music-note-beamed',
    gradient: 'linear-gradient(135deg, #11998e, #38ef7d)',
    tag: 'malayalam',
    description: 'Mollywood songs and Kerala vibes',
    group: 'language',
    sources: { itunes: 'malayalam songs' },
  },
  {
    id: 'kannada',
    name: 'Kannada',
    icon: 'bi-music-note-beamed',
    gradient: 'linear-gradient(135deg, #c94b4b, #4b134f)',
    tag: 'kannada',
    description: 'Sandalwood hits',
    group: 'language',
    sources: { itunes: 'kannada songs' },
  },
  {
    id: 'marathi',
    name: 'Marathi',
    icon: 'bi-music-note-beamed',
    gradient: 'linear-gradient(135deg, #ee9ca7, #ffdde1)',
    tag: 'marathi',
    description: 'Marathi film and folk songs',
    group: 'language',
    sources: { itunes: 'marathi songs' },
  },
  {
    id: 'bengali',
    name: 'Bengali',
    icon: 'bi-music-note-beamed',
    gradient: 'linear-gradient(135deg, #8e2de2, #4a00e0)',
    tag: 'bengali',
    description: 'Bengali film songs, Rabindra Sangeet and bands',
    group: 'language',
    sources: { itunes: 'bengali songs', audius: ['bengali'] },
  },
  {
    id: 'bhojpuri',
    name: 'Bhojpuri',
    icon: 'bi-music-note-beamed',
    gradient: 'linear-gradient(135deg, #fc4a1a, #f7b733)',
    tag: 'bhojpuri',
    description: 'Bhojpuri chartbusters',
    group: 'language',
    sources: { itunes: 'bhojpuri' },
  },
  {
    id: 'gujarati',
    name: 'Gujarati',
    icon: 'bi-music-note-beamed',
    gradient: 'linear-gradient(135deg, #e65c00, #f9d423)',
    tag: 'gujarati',
    description: 'Garba, dandiya and Gujarati hits',
    group: 'language',
    sources: { itunes: 'gujarati garba' },
  },
  {
    id: 'ladakhi',
    name: 'Ladakhi',
    icon: 'bi-snow2',
    gradient: 'linear-gradient(135deg, #667eea, #764ba2)',
    tag: 'ladakhi',
    description: 'Ladakhi folk and fusion from the high passes',
    group: 'language',
    sources: { audius: ['ladakh', 'tibetan'], itunes: 'ladakhi', archive: 'ladakh' },
  },
  {
    id: 'tibet',
    name: 'Tibetan',
    icon: 'bi-flower1',
    gradient: 'linear-gradient(135deg, #f093fb, #f5576c)',
    tag: 'tibet',
    description: 'Tibetan chants and modern Himalayan melodies',
    group: 'language',
    sources: { uploads: 'Tibetan', audius: ['tibetan', 'singing bowl'], itunes: 'tibetan', archive: 'tibetan music' },
  },
  {
    id: 'nepal',
    name: 'Nepali',
    icon: 'bi-geo-alt-fill',
    gradient: 'linear-gradient(135deg, #ffecd2, #fcb69f)',
    tag: 'nepal',
    description: 'Folk and modern pop from Nepal',
    group: 'language',
    sources: { itunes: 'nepali songs', audius: ['nepali', 'nepal'] },
  },
  {
    id: 'pahadi',
    name: 'Pahadi',
    icon: 'bi-triangle-fill',
    gradient: 'linear-gradient(135deg, #f093fb, #f5576c)',
    tag: 'pahadi',
    description: 'Melodies from the Himalayan foothills',
    group: 'language',
    sources: { itunes: 'pahadi', audius: ['pahadi'] },
  },
  {
    id: 'uttarakhand',
    name: 'Uttarakhand',
    icon: 'bi-tree-fill',
    gradient: 'linear-gradient(135deg, #43e97b, #38f9d7)',
    tag: 'uttarakhand',
    description: 'Garhwali and Kumaoni songs',
    group: 'language',
    sources: { itunes: 'garhwali', audius: ['pahadi'] },
  },
  {
    id: 'himachali',
    name: 'Himachali',
    icon: 'bi-snow',
    gradient: 'linear-gradient(135deg, #a1c4fd, #c2e9fb)',
    tag: 'himachali',
    description: 'Folk songs from Himachal',
    group: 'language',
    sources: { itunes: 'himachali', audius: ['himachal'] },
  },
  {
    id: 'pakistan',
    name: 'Pakistani & Sufi',
    icon: 'bi-moon-stars-fill',
    gradient: 'linear-gradient(135deg, #4facfe, #00f2fe)',
    tag: 'pakistan',
    description: 'Sufi, qawwali and Pakistani hits',
    group: 'language',
    sources: { itunes: 'coke studio', audius: ['sufi', 'qawwali'] },
  },
  {
    id: 'india',
    name: 'Popular India',
    icon: 'bi-music-note-beamed',
    gradient: 'linear-gradient(135deg, #89f7fe, #66a6ff)',
    tag: 'india',
    description: 'Top tracks from across India',
    group: 'language',
    sources: { itunes: 'arijit singh', audius: ['india', 'desi'] },
  },
  {
    id: 'kpop',
    name: 'K-Pop',
    icon: 'bi-stars',
    gradient: 'linear-gradient(135deg, #ff6a88, #ff99ac)',
    tag: 'kpop',
    description: 'Korean pop hits',
    group: 'language',
    sources: { itunes: 'k-pop', itunesCountry: 'KR', audius: ['kpop'] },
  },
  {
    id: 'jpop',
    name: 'J-Pop & Anime',
    icon: 'bi-brightness-alt-high',
    gradient: 'linear-gradient(135deg, #fbc2eb, #a6c1ee)',
    tag: 'jpop',
    description: 'Japanese pop and anime themes',
    group: 'language',
    sources: { itunes: 'j-pop', itunesCountry: 'JP', audius: ['anime', 'jpop'] },
  },
  {
    id: 'arabic',
    name: 'Arabic',
    icon: 'bi-moon',
    gradient: 'linear-gradient(135deg, #b79891, #94716b)',
    tag: 'arabic',
    description: 'Arabic pop and classics',
    group: 'language',
    sources: { itunes: 'arabic hits', itunesCountry: 'AE', audius: ['arabic'] },
  },
  {
    id: 'spanish',
    name: 'Spanish & Reggaeton',
    icon: 'bi-sun-fill',
    gradient: 'linear-gradient(135deg, #f12711, #f5af19)',
    tag: 'spanish',
    description: 'Reggaeton, Latin pop and urbano',
    group: 'language',
    sources: { itunes: 'reggaeton', itunesCountry: 'US', audiusGenre: 'Latin' },
  },
  {
    id: 'afro',
    name: 'Afrobeats',
    icon: 'bi-globe-europe-africa',
    gradient: 'linear-gradient(135deg, #f09819, #edde5d)',
    tag: 'afro',
    description: 'Afrobeats and amapiano',
    group: 'language',
    sources: { itunes: 'afrobeats', itunesCountry: 'NG', audius: ['afrobeats', 'amapiano'] },
  },
  {
    id: 'turkish',
    name: 'Turkish',
    icon: 'bi-music-note-beamed',
    gradient: 'linear-gradient(135deg, #e53935, #e35d5b)',
    tag: 'turkish',
    description: 'Turkish pop hits',
    group: 'language',
    sources: { itunes: 'turkish pop', itunesCountry: 'TR' },
  },
  {
    id: 'cpop',
    name: 'Chinese',
    icon: 'bi-music-note-beamed',
    gradient: 'linear-gradient(135deg, #d31027, #ea384d)',
    tag: 'cpop',
    description: 'Mandarin and Cantonese pop',
    group: 'language',
    sources: { itunes: 'mandopop', itunesCountry: 'TW' },
  },
  {
    id: 'english',
    name: 'English Hits',
    icon: 'bi-broadcast-pin',
    gradient: 'linear-gradient(135deg, #3a7bd5, #3a6073)',
    tag: 'english',
    description: 'Global chart hits',
    group: 'language',
    sources: { uploads: 'English', itunes: 'top hits 2025', itunesCountry: 'US', audiusGenre: 'Pop' },
  },
  {
    id: 'pop',
    name: 'Pop',
    icon: 'bi-balloon-heart-fill',
    gradient: 'linear-gradient(135deg, #fc466b, #3f5efb)',
    tag: 'pop',
    description: 'Catchy hooks and feel-good pop',
    group: 'genre',
    sources: { audiusGenre: 'Pop', itunes: 'top pop hits', itunesCountry: 'US' },
  },
  {
    id: 'hiphop',
    name: 'Hip-Hop',
    icon: 'bi-mic-fill',
    gradient: 'linear-gradient(135deg, #f7971e, #ffd200)',
    tag: 'hiphop',
    description: 'Rap and hip-hop trending now',
    group: 'genre',
    sources: { audiusGenre: 'Hip-Hop/Rap', itunes: 'desi hip hop' },
  },
  {
    id: 'trap',
    name: 'Trap',
    icon: 'bi-speaker-fill',
    gradient: 'linear-gradient(135deg, #232526, #414345)',
    tag: 'trap',
    description: 'Hard-hitting 808s',
    group: 'genre',
    sources: { audiusGenre: 'Trap' },
  },
  {
    id: 'rnb',
    name: 'R&B & Soul',
    icon: 'bi-heart-pulse-fill',
    gradient: 'linear-gradient(135deg, #b24592, #f15f79)',
    tag: 'rnb',
    description: 'Smooth R&B and soul',
    group: 'genre',
    sources: { audiusGenre: 'R&B/Soul', itunes: 'r&b hits', itunesCountry: 'US' },
  },
  {
    id: 'electronic',
    name: 'Electronic',
    icon: 'bi-lightning-charge-fill',
    gradient: 'linear-gradient(135deg, #00c6ff, #0072ff)',
    tag: 'electronic',
    description: 'Everything with a synth in it',
    group: 'genre',
    sources: { audiusGenre: 'Electronic' },
  },
  {
    id: 'house',
    name: 'House',
    icon: 'bi-house-heart-fill',
    gradient: 'linear-gradient(135deg, #7f00ff, #e100ff)',
    tag: 'house',
    description: 'House, deep house and tech house',
    group: 'genre',
    sources: { audiusGenre: 'House', audius: ['deep house'] },
  },
  {
    id: 'techno',
    name: 'Techno',
    icon: 'bi-cpu-fill',
    gradient: 'linear-gradient(135deg, #0f2027, #2c5364)',
    tag: 'techno',
    description: 'Warehouse techno',
    group: 'genre',
    sources: { audiusGenre: 'Techno' },
  },
  {
    id: 'dnb',
    name: 'Drum & Bass',
    icon: 'bi-activity',
    gradient: 'linear-gradient(135deg, #56ab2f, #a8e063)',
    tag: 'dnb',
    description: 'Fast breaks and heavy bass',
    group: 'genre',
    sources: { audiusGenre: 'Drum & Bass' },
  },
  {
    id: 'dubstep',
    name: 'Dubstep',
    icon: 'bi-soundwave',
    gradient: 'linear-gradient(135deg, #8e0e00, #1f1c18)',
    tag: 'dubstep',
    description: 'Wobbles and drops',
    group: 'genre',
    sources: { audiusGenre: 'Dubstep' },
  },
  {
    id: 'trance',
    name: 'Trance',
    icon: 'bi-infinity',
    gradient: 'linear-gradient(135deg, #4568dc, #b06ab3)',
    tag: 'trance',
    description: 'Euphoric trance',
    group: 'genre',
    sources: { audiusGenre: 'Trance' },
  },
  {
    id: 'rock',
    name: 'Rock',
    icon: 'bi-lightning-fill',
    gradient: 'linear-gradient(135deg, #cb2d3e, #ef473a)',
    tag: 'rock',
    description: 'Guitars up',
    group: 'genre',
    sources: { audiusGenre: 'Rock', itunes: 'rock classics', itunesCountry: 'US' },
  },
  {
    id: 'metal',
    name: 'Metal',
    icon: 'bi-fire',
    gradient: 'linear-gradient(135deg, #000000, #434343)',
    tag: 'metal',
    description: 'Heavy riffs',
    group: 'genre',
    sources: { audiusGenre: 'Metal' },
  },
  {
    id: 'punk',
    name: 'Punk',
    icon: 'bi-exclamation-diamond-fill',
    gradient: 'linear-gradient(135deg, #ed213a, #93291e)',
    tag: 'punk',
    description: 'Fast, loud and short',
    group: 'genre',
    sources: { audiusGenre: 'Punk' },
  },
  {
    id: 'indie',
    name: 'Indie & Alternative',
    icon: 'bi-stars',
    gradient: 'linear-gradient(135deg, #a1c4fd, #c2e9fb)',
    tag: 'indie',
    description: 'Independent artists and alt sounds',
    group: 'genre',
    sources: { uploads: 'Indie', audiusGenre: 'Alternative', audius: ['indie'] },
  },
  {
    id: 'jazz',
    name: 'Jazz',
    icon: 'bi-music-note-list',
    gradient: 'linear-gradient(135deg, #b79891, #94716b)',
    tag: 'jazz',
    description: 'Smooth, bebop and modern jazz',
    group: 'genre',
    sources: { audiusGenre: 'Jazz', archive: 'jazz' },
  },
  {
    id: 'blues',
    name: 'Blues',
    icon: 'bi-droplet-fill',
    gradient: 'linear-gradient(135deg, #1e3c72, #2a5298)',
    tag: 'blues',
    description: 'Classic and modern blues',
    group: 'genre',
    sources: { audiusGenre: 'Blues', archive: 'blues' },
  },
  {
    id: 'classical',
    name: 'Classical',
    icon: 'bi-vector-pen',
    gradient: 'linear-gradient(135deg, #c471f5, #fa71cd)',
    tag: 'classical',
    description: 'Western and Indian classical',
    group: 'genre',
    sources: { audiusGenre: 'Classical', itunes: 'indian classical', archive: 'classical music' },
  },
  {
    id: 'country',
    name: 'Country',
    icon: 'bi-sunset-fill',
    gradient: 'linear-gradient(135deg, #d38312, #a83279)',
    tag: 'country',
    description: 'Country and americana',
    group: 'genre',
    sources: { audiusGenre: 'Country', itunes: 'country hits', itunesCountry: 'US' },
  },
  {
    id: 'latin',
    name: 'Latin',
    icon: 'bi-sun',
    gradient: 'linear-gradient(135deg, #f12711, #f5af19)',
    tag: 'latin',
    description: 'Latin rhythms',
    group: 'genre',
    sources: { audiusGenre: 'Latin' },
  },
  {
    id: 'reggae',
    name: 'Reggae & Dancehall',
    icon: 'bi-peace-fill',
    gradient: 'linear-gradient(135deg, #009245, #fcee21)',
    tag: 'reggae',
    description: 'Reggae, dub and dancehall',
    group: 'genre',
    sources: { audiusGenre: 'Reggae', audius: ['dancehall'] },
  },
  {
    id: 'funk',
    name: 'Funk & Disco',
    icon: 'bi-disc-fill',
    gradient: 'linear-gradient(135deg, #fe8c00, #f83600)',
    tag: 'funk',
    description: 'Grooves and disco',
    group: 'genre',
    sources: { audiusGenre: 'Funk', audius: ['disco'] },
  },
  {
    id: 'folk',
    name: 'Folk',
    icon: 'bi-vinyl',
    gradient: 'linear-gradient(135deg, #d4fc79, #96e6a1)',
    tag: 'folk',
    description: 'Traditional and modern folk',
    group: 'genre',
    sources: { uploads: 'Folk', audiusGenre: 'Folk', audius: ['folk'], archive: 'folk music' },
  },
  {
    id: 'acoustic',
    name: 'Acoustic',
    icon: 'bi-music-note',
    gradient: 'linear-gradient(135deg, #c79081, #dfa579)',
    tag: 'acoustic',
    description: 'Unplugged guitars and intimate vocals',
    group: 'genre',
    sources: { audiusGenre: 'Acoustic', audius: ['unplugged'] },
  },
  {
    id: 'lofi',
    name: 'Lo-Fi',
    icon: 'bi-cup-hot',
    gradient: 'linear-gradient(135deg, #2af598, #009efd)',
    tag: 'lofi',
    description: 'Beats to study and relax to',
    group: 'genre',
    sources: { audiusGenre: 'Lo-Fi', audius: ['lofi'] },
  },
  {
    id: 'ambient',
    name: 'Ambient',
    icon: 'bi-cloud-fog2-fill',
    gradient: 'linear-gradient(135deg, #bdc3c7, #2c3e50)',
    tag: 'ambient',
    description: 'Textures and drones',
    group: 'genre',
    sources: { audiusGenre: 'Ambient' },
  },
  {
    id: 'soundtrack',
    name: 'Soundtrack & Cinematic',
    icon: 'bi-camera-reels-fill',
    gradient: 'linear-gradient(135deg, #141e30, #243b55)',
    tag: 'soundtrack',
    description: 'Scores and epic cinematic music',
    group: 'genre',
    sources: { audiusGenre: 'Soundtrack' },
  },
  {
    id: 'world',
    name: 'World',
    icon: 'bi-globe2',
    gradient: 'linear-gradient(135deg, #1d976c, #93f9b9)',
    tag: 'world',
    description: 'Sounds from everywhere',
    group: 'genre',
    sources: { audiusGenre: 'World' },
  },
  {
    id: 'devotional',
    name: 'Devotional',
    icon: 'bi-brightness-high',
    gradient: 'linear-gradient(135deg, #f7b733, #fc4a1a)',
    tag: 'devotional',
    description: 'Bhajans, kirtan, mantras and gospel',
    group: 'genre',
    sources: { audiusGenre: 'Devotional', itunes: 'bhajan' },
  },
  {
    id: 'experimental',
    name: 'Experimental',
    icon: 'bi-radioactive',
    gradient: 'linear-gradient(135deg, #3a1c71, #d76d77)',
    tag: 'experimental',
    description: 'Out-there sounds',
    group: 'genre',
    sources: { audiusGenre: 'Experimental' },
  },
  {
    id: 'kids',
    name: 'Kids',
    icon: 'bi-emoji-smile-fill',
    gradient: 'linear-gradient(135deg, #fceabb, #f8b500)',
    tag: 'kids',
    description: 'Songs for little ones',
    group: 'genre',
    sources: { audiusGenre: 'Kids', itunes: 'nursery rhymes', itunesCountry: 'US' },
  },
  {
    id: 'podcasts',
    name: 'Podcasts & Talk',
    icon: 'bi-mic',
    gradient: 'linear-gradient(135deg, #3c3b3f, #605c3c)',
    tag: 'podcasts',
    description: 'Podcasts, spoken word and comedy',
    group: 'genre',
    sources: { audiusGenre: 'Podcasts', audius: ['spoken word', 'comedy'] },
  },
  {
    id: 'oldies',
    name: 'Golden Oldies',
    icon: 'bi-vinyl-fill',
    gradient: 'linear-gradient(135deg, #8e9eab, #eef2f3)',
    tag: 'oldies',
    description: 'Historic recordings from the 78rpm era',
    group: 'genre',
    sources: { archive: 'collection:78rpm', itunes: 'old hindi songs' },
  },
  {
    id: 'chill',
    name: 'Chill',
    icon: 'bi-cloud-moon',
    gradient: 'linear-gradient(135deg, #cfd9df, #e2ebf0)',
    tag: 'chill',
    description: 'Unwind and slow down',
    group: 'mood',
    sources: { uploads: 'Chill', audiusGenre: 'Downtempo', audius: ['chill'] },
  },
  {
    id: 'workout',
    name: 'Workout',
    icon: 'bi-heart-pulse',
    gradient: 'linear-gradient(135deg, #ff416c, #ff4b2b)',
    tag: 'workout',
    description: 'High-energy tracks to push harder',
    group: 'mood',
    sources: { audius: ['workout', 'gym', 'edm'], itunes: 'workout hits', itunesCountry: 'US' },
  },
  {
    id: 'focus',
    name: 'Focus',
    icon: 'bi-bullseye',
    gradient: 'linear-gradient(135deg, #4ca1af, #c4e0e5)',
    tag: 'focus',
    description: 'Instrumentals for deep work',
    group: 'mood',
    sources: { audius: ['focus', 'study', 'instrumental'], audiusGenre: 'Lo-Fi' },
  },
  {
    id: 'sleep',
    name: 'Sleep',
    icon: 'bi-moon-stars',
    gradient: 'linear-gradient(135deg, #0f0c29, #302b63)',
    tag: 'sleep',
    description: 'Gentle sounds to drift off',
    group: 'mood',
    sources: { audius: ['sleep', 'rain', 'calm piano'] },
  },
  {
    id: 'party',
    name: 'Party',
    icon: 'bi-balloon-fill',
    gradient: 'linear-gradient(135deg, #ec008c, #fc6767)',
    tag: 'party',
    description: 'Turn it up',
    group: 'mood',
    sources: { audius: ['party', 'dance'], itunes: 'party songs' },
  },
  {
    id: 'romance',
    name: 'Romance',
    icon: 'bi-heart-fill',
    gradient: 'linear-gradient(135deg, #ee0979, #ff6a00)',
    tag: 'romance',
    description: 'Love songs',
    group: 'mood',
    sources: { itunes: 'romantic songs', audius: ['love song'] },
  },
  {
    id: 'sad',
    name: 'Sad & Heartbreak',
    icon: 'bi-cloud-drizzle-fill',
    gradient: 'linear-gradient(135deg, #606c88, #3f4c6b)',
    tag: 'sad',
    description: 'For the feels',
    group: 'mood',
    sources: { itunes: 'sad songs', audius: ['sad'] },
  },
  {
    id: 'happy',
    name: 'Feel Good',
    icon: 'bi-emoji-sunglasses-fill',
    gradient: 'linear-gradient(135deg, #f9d423, #ff4e50)',
    tag: 'happy',
    description: 'Instant good mood',
    group: 'mood',
    sources: { audius: ['happy', 'feel good'], itunes: 'feel good songs', itunesCountry: 'US' },
  },
  {
    id: 'meditation',
    name: 'Meditation & Zen',
    icon: 'bi-yin-yang',
    gradient: 'linear-gradient(135deg, #a18cd1, #fbc2eb)',
    tag: 'meditation',
    description: 'Peaceful sounds for mindfulness',
    group: 'mood',
    sources: { uploads: 'Meditation', audiusGenre: 'Ambient', audius: ['meditation'] },
  },
  {
    id: 'roadtrip',
    name: 'Road Trip',
    icon: 'bi-car-front-fill',
    gradient: 'linear-gradient(135deg, #1488cc, #2b32b2)',
    tag: 'roadtrip',
    description: 'Windows down, volume up',
    group: 'mood',
    sources: { audius: ['road trip', 'drive'], itunes: 'road trip songs' },
  },
  {
    id: 'radio',
    name: 'Radio India',
    icon: 'bi-boombox',
    gradient: 'linear-gradient(135deg, #ff0844, #ffb199)',
    tag: 'radio',
    description: 'Live stations from across India',
    group: 'radio',
    sources: { radio: 'india' },
  },
  {
    id: 'radio-bollywood',
    name: 'Bollywood Radio',
    icon: 'bi-film',
    gradient: 'linear-gradient(135deg, #f6d365, #fda085)',
    tag: 'radio-bollywood',
    description: '24/7 Bollywood stations',
    group: 'radio',
    sources: { radio: 'bollywood' },
  },
  {
    id: 'radio-nepal',
    name: 'Radio Nepal',
    icon: 'bi-geo-alt-fill',
    gradient: 'linear-gradient(135deg, #ffecd2, #fcb69f)',
    tag: 'radio-nepal',
    description: 'Live FM from Nepal',
    group: 'radio',
    sources: { radio: 'nepal' },
  },
  {
    id: 'radio-hits',
    name: 'Global Hits Radio',
    icon: 'bi-broadcast',
    gradient: 'linear-gradient(135deg, #fc466b, #3f5efb)',
    tag: 'radio-hits',
    description: 'Pop hit stations worldwide',
    group: 'radio',
    sources: { radio: 'tag:pop' },
  },
  {
    id: 'radio-news',
    name: 'News & Talk',
    icon: 'bi-newspaper',
    gradient: 'linear-gradient(135deg, #606c88, #3f4c6b)',
    tag: 'radio-news',
    description: 'News and talk stations',
    group: 'radio',
    sources: { radio: 'tag:news' },
  },
  {
    id: 'radio-lofi',
    name: 'Lo-Fi Radio',
    icon: 'bi-cup-hot',
    gradient: 'linear-gradient(135deg, #2af598, #009efd)',
    tag: 'radio-lofi',
    description: 'Nonstop lo-fi streams',
    group: 'radio',
    sources: { radio: 'lofi' },
  },
  {
    id: 'radio-jazz',
    name: 'Jazz Radio',
    icon: 'bi-music-note-list',
    gradient: 'linear-gradient(135deg, #b79891, #94716b)',
    tag: 'radio-jazz',
    description: 'Round-the-clock jazz',
    group: 'radio',
    sources: { radio: 'jazz' },
  },
  {
    id: 'radio-classical',
    name: 'Classical Radio',
    icon: 'bi-vector-pen',
    gradient: 'linear-gradient(135deg, #c471f5, #fa71cd)',
    tag: 'radio-classical',
    description: 'Classical stations',
    group: 'radio',
    sources: { radio: 'classical' },
  },
  {
    id: 'radio-devotional',
    name: 'Devotional Radio',
    icon: 'bi-brightness-high',
    gradient: 'linear-gradient(135deg, #f7b733, #fc4a1a)',
    tag: 'radio-devotional',
    description: 'Bhajans and spiritual stations',
    group: 'radio',
    sources: { radio: 'tag:devotional' },
  },
  {
    id: 'radio-tibet',
    name: 'Tibetan & Buddhist Radio',
    icon: 'bi-flower3',
    gradient: 'linear-gradient(135deg, #f093fb, #f5576c)',
    tag: 'radio-tibet',
    description: 'Chants and mantras',
    group: 'radio',
    sources: { radio: 'tibet' },
  },
];

export const CATEGORY_GROUPS: { id: NonNullable<MusicCategory['group']>; title: string }[] = [
  { id: 'genre', title: 'Genres' },
  { id: 'language', title: 'Languages & Regions' },
  { id: 'mood', title: 'Moods & Moments' },
  { id: 'radio', title: 'Live Radio' },
];
